CREATE DATABASE Cinema;
GO
GO
USE Cinema;
Go
CREATE TABLE Films(
FilmId INT NOT NULL IDENTITY(1,1) PRIMARY KEY ,
FilmName NVARCHAR(100) NOT NULL
)
GO
CREATE TABLE Halls(
HallId INT NOT NULL IDENTITY(1,1) PRIMARY KEY ,
HallName NVARCHAR(100) NOT NULL,
PlacesCount INT NOT NULL,
RowsCount INT NOT NULL,
ColumnsCount INT NOT NULL
)
GO
CREATE TABLE Shedule(
SheduleId INT NOT NULL IDENTITY(1,1) PRIMARY KEY ,
FilmId INT FOREIGN KEY REFERENCES Films(FilmId) not null,
MovieTime DATETIME2 NOT NULL,
HallId INT FOREIGN KEY REFERENCES Halls(HallId) NOT NULL
)
GO
CREATE TABLE Places(
PlaceId INT NOT NULL IDENTITY(1,1) PRIMARY KEY ,
SheduleId INT NOT NULL FOREIGN KEY REFERENCES Shedule(SheduleId),
PlaceStatus NVARCHAR(100) ,
RowNumber INT ,
ColumnNumber INT
)
